"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

setup(
    app=[ 'macApp.py' ],
    options=dict(
        py2app=dict(
            packages=['wx'],
            includes=['mako.cache'],
            resources=['constructor/resources', 'constructor/blocks'],
            plist=dict(
				CFBundleName               = "Processes",
				CFBundleShortVersionString = "0.0.1",     # must be in X.X.X format
				CFBundleGetInfoString      = "Processes 0.0.1",
				CFBundleExecutable         = "Processes",
				CFBundleIdentifier         = "uk.co.jonsimpson.Processes",
			),
        )
    ),
    setup_requires=['py2app'],
)
